### ISSUE TITLE
when trying to place new filters 

### ISSUE THREAD

**Issue by sketchgithub** [bakape/meguca#287]
-ubuntu64:~/server/config$ warn: Running in (insecure) debug mode.
warn: Do not use on the public internet.
/home/meguca/server/config/hot.js:91

Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/home/meguca/server/server/web/index.js:24:8)
    at Module._compile (module.js:434:26)
    at normalLoader (/home/meguca/server/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/meguca/server/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
warn: Do not use on the public internet.
/home/meguca/server/config/hot.js:91
	FILTER: [{p: what, r: 'que'}],
	             ^

ReferenceError: what is not defined
    at Object.<anonymous> (/home/meguca/server/config/hot.js:91:15)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/meguca/server/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/meguca/server/server/state.js:6:40)
    at Module._compile (module.js:434:26)
(reverse-i-search)`': ^C

**Comment by bakape** [comment]
2 things. First it's already running and I guess you overwrote the pid. Kill it with `killall node`.
Next you have a "what" in you hot.js, that is not quoted.

**Comment by sketchgithub** [comment]
oh the comment didnt have quotes on the first term

"Word replacament filter. {p: /foo/, r: 'bar'} Pattern must not contain spaces
 or newlines"

**Comment by sketchgithub** [comment]
the comments on the code are what help the most for getting this running, thanks for those.

**Comment by sketchgithub** [comment]
fixed. i get bad persona when i log in though

**Comment by bakape** [comment]
You probably have misconfigured PERSONA_AUDIENCE. Set it to `${protocol}://${domain}:${port}` as shown on https://developer.mozilla.org/en-US/Persona/Quick_Setup

**Comment by sketchgithub** [comment]
I believe I did this correctly but it is still not working.

// URL and domain of the website
        PERSONA_AUDIENCE: 'http://notjesus.xyz:8000',
        LOGIN_SESSION_TIME: 60*60*24*14,

**Comment by bakape** [comment]
The port is 80 (standard HTTP port), not 8000.

**Comment by sketchgithub** [comment]
the example shows it as 'http://localhost:8000'

**Comment by bakape** [comment]
That's for development.
