### ISSUE TITLE
Doesn't work after update, when compile

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#396]
I tried to update meguca.

make clean

make update

make

On this step was error 

`[17:29:50] Finished 'css' after 2.04 s
client/state.ts(98,9): error TS2322: Type 'Promise<[Set<number>, Set<number>, Set<number>]>' is not assignable to type 'Promise<void>'.
  Type '[Set<number>, Set<number>, Set<number>]' is not assignable to type 'void'.
/home/meguca/gulpfile.js:123
                throw err
                ^

TypeScript error: client/state.ts(98,9): error TS2322: Type 'Promise<[Set<number>, Set<number>, Set<number>]>' is not assignable to type 'Promise<void>'.
  Type '[Set<number>, Set<number>, Set<number>]' is not assignable to type 'void'.
    at Object.getError (/home/meguca/node_modules/gulp-typescript/release/utils.js:55:15)
    at Output.getError (/home/meguca/node_modules/gulp-typescript/release/output.js:91:22)
    at Output.diagnostic (/home/meguca/node_modules/gulp-typescript/release/output.js:94:25)
    at ProjectCompiler.reportDiagnostics (/home/meguca/node_modules/gulp-typescript/release/compiler.js:125:33)
    at ProjectCompiler.inputDone (/home/meguca/node_modules/gulp-typescript/release/compiler.js:47:14)
    at CompileStream.end (/home/meguca/node_modules/gulp-typescript/release/project.js:125:31)
    at DestroyableTransform.onend (/home/meguca/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
Makefile:42: recipe for target 'client' failed
make: *** [client] Error 1`

And make was stopped.

**Comment by bakape** [comment]
Already fixed in 0473d44. Pull the latest changes.

**Comment by serofir** [comment]
No, it still not working after all.

**Comment by bakape** [comment]
Did you pull the latest changes with `git pull`?

**Comment by serofir** [comment]
fatal: 'meguca' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by bakape** [comment]
Well, that is the problem. You did not download it with git or deleted
something you should not have.

**Comment by serofir** [comment]
Ok, I tried to fix it manual, and it works now.
