### ISSUE TITLE
Weird error when compiling

### ISSUE THREAD

**Issue by RaymondSchnyder** [bakape/meguca#403]
Hey,

First, thank your making this awesome Software, i cant wait to use it with my friends!
Second, i tried to compile your Software, but im not getting it to work actually :/

This is the error stack i get, (I use go 1.6):

client/hover.ts(50,55): error TS2345: Argument of type '{ passive: boolean; }' is not assignable to parameter of type 'boolean'.
/home/user/meguca/meguca-2.7.1/gulpfile.js:123
                throw err
                ^

TypeScript error: client/hover.ts(50,55): error TS2345: Argument of type '{ passive: boolean; }' is not assignable to parameter of type 'boolean'.
    at Object.getError (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/utils.js:55:15)
    at Output.getError (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/output.js:91:22)
    at Output.diagnostic (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/output.js:94:25)
    at ProjectCompiler.reportDiagnostics (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/compiler.js:125:33)
    at ProjectCompiler.inputDone (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/compiler.js:47:14)
    at CompileStream.end (/home/user/meguca/meguca-2.7.1/node_modules/gulp-typescript/release/project.js:125:31)
    at DestroyableTransform.onend (/home/user/meguca/meguca-2.7.1/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
Makefile:42: recipe for target 'client' failed
make: *** [client] Error 1

Thank you for helping :-)

Have a nice day

**Comment by bakape** [comment]
Looks like a bug after a TypeScript update. Should be fixed now.
