### ISSUE TITLE
Ban formatting on modlog sometimes panics

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#959]
```
server: 2600:8801:2900:1066:e4c6:2677:f904:8af: &errors.errorString{s:"invalid ban format strings: []"} goroutine 497634 [running]: runtime/debug.Stack(0xc000610800, 0xc000d24a78, 0x26) /usr/local/go/src/runtime/debug/stack.go:24 +0xa7 meguca/server.handlePanic(0xcd9760, 0xc00138f340, 0xc000610800, 0xb3db20, 0xc001603be0) /home/meguca/imager/server/src/meguca/server/router.go:73 +0x105 github.com/dimfeld/httptreemux.(*TreeMux).serveHTTPPanic(0xc000283540, 0xcd9760, 0xc00138f340, 0xc000610800) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:68 +0x79 panic(0xb3db20, 0xc001603be0) /usr/local/go/src/runtime/panic.go:513 +0x1b9 meguca/templates.StreamBanPage(0xc001318070, 0xc00119b230, 0x26, 0xc0011960d0, 0x3, 0x0, 0xc0011960d4, 0xc, 0xc0011960e0, 0x6, ...) auth.qtpl:36 +0x715 meguca/templates.WriteBanPage(0xcd3980, 0xc001c35ca0, 0xc00119b230, 0x26, 0xc0011960d0, 0x3, 0x0, 0xc0011960d4, 0xc, 0xc0011960e0, ...) auth.qtpl:56 +0x6e meguca/templates.BanPage(0xc00119b230, 0x26, 0xc0011960d0, 0x3, 0x0, 0xc0011960d4, 0xc, 0xc0011960e0, 0x6, 0x4407c58, ...) auth.qtpl:56 +0x75 meguca/server.assertNotBanned(0xcd9760, 0xc00138f340, 0xc000610900, 0xc049e1, 0x3, 0x41d228) /home/meguca/imager/server/src/meguca/server/util.go:132 +0x309 meguca/server.serveNewCaptcha(0xcd9760, 0xc00138f340, 0xc000610900) /home/meguca/imager/server/src/meguca/server/captcha.go:62 +0x8f github.com/dimfeld/httptreemux.(*ContextGroup).Handle.func1(0xcd9760, 0xc00138f340, 0xc000610800, 0xc00056afc0) /home/meguca/go/src/github.com/dimfeld/httptreemux/context.go:55 +0x11f github.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc000283540, 0xcd9760, 0xc00138f340, 0xc000610800, 0xc8, 0xc0003a7b40, 0xc00056afc0, 0x0) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:247 +0x79 github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc000283540, 0xcd9760, 0xc00138f340, 0xc000610800) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:268 +0xe3 net/http.serverHandler.ServeHTTP(0xc000293520, 0xcd9760, 0xc00138f340, 0xc000610800) /usr/local/go/src/net/http/server.go:2741 +0xab net/http.(*conn).serve(0xc0013ecdc0, 0xcda4e0, 0xc000a53300) /usr/local/go/src/net/http/server.go:1847 +0x646 created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by Chiiruno** [comment]
What do you think this is caused by?

**Comment by bakape** [comment]
This used to be an out of bounds indexing, before I added that check. As to what exactly caused it, did not have the time to check back then.
