### ISSUE TITLE
nil dereference in youtube fetch

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#988]
```
server: 31.49.40.24: "invalid memory address or nil pointer dereference" goroutine 819538 [running]: runtime/debug.Stack(0xc001031500, 0xc002fe4110, 0xb) /usr/local/go/src/runtime/debug/stack.go:24 +0xa7 meguca/server.handlePanic(0xd1a9a0, 0xc000de5a40, 0xc001031500, 0xb89de0, 0x13d4660) /home/meguca/server/server/src/meguca/server/router.go:80 +0x105 github.com/dimfeld/httptreemux.(*TreeMux).serveHTTPPanic(0xc00009ac80, 0xd1a9a0, 0xc000de5a40, 0xc001031500) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:68 +0x79 panic(0xb89de0, 0x13d4660) /usr/local/go/src/runtime/panic.go:513 +0x1b9 meguca/server.getYouTubeInfo(0xc0039087c6, 0xb, 0x2, 0xc0039087c6, 0xb, 0xd1b701) /home/meguca/server/server/src/meguca/server/embed.go:64 +0x1bc meguca/server.youTubeData(0xd1a9a0, 0xc000de5a40, 0xc001031800) /home/meguca/server/server/src/meguca/server/embed.go:16 +0x5c github.com/dimfeld/httptreemux.(*ContextGroup).Handle.func1(0xd1a9a0, 0xc000de5a40, 0xc001031500, 0xc002324000) /home/meguca/go/src/github.com/dimfeld/httptreemux/context.go:55 +0x11f github.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc00009ac80, 0xd1a9a0, 0xc000de5a40, 0xc001031500, 0xc8, 0xc0001b6810, 0xc002324000, 0x0) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:247 +0x79 github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc00009ac80, 0xd1a9a0, 0xc000de5a40, 0xc001031500) /home/meguca/go/src/github.com/dimfeld/httptreemux/router.go:268 +0xe3 net/http.serverHandler.ServeHTTP(0xc00049d110, 0xd1a9a0, 0xc000de5a40, 0xc001031500) /usr/local/go/src/net/http/server.go:2741 +0xab net/http.(*conn).serve(0xc0011017c0, 0xd1b6e0, 0xc0037feec0) /usr/local/go/src/net/http/server.go:1847 +0x646 created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2851 +0x2f5

**Comment by Chiiruno** [comment]
The only place this can happen, from what I can see, is https://github.com/bakape/meguca/blob/master/server/src/meguca/server/embed.go#L15 .
This indicates a problem with router, I think.
Thoughts?

**Comment by Chiiruno** [comment]
A fix I guess would be to check if the pointer is nil before using extractparam, but I'm not sure that's the actual problem.

**Comment by bakape** [comment]
You are closing the response body before checking for errors and thus dereference res, the the response can be nil.
